# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Buscar medico.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 462)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("*{\n"
"    background-color: rgb(0, 0, 0);\n"
"    font-family: Arial;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QMenuBar{\n"
"    text-decoration: underline rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 75 18pt;\n"
"}\n"
"\n"
"QLineEdit,QComboBox,QDoubleSpinBox,QSpinBox{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton{\n"
"  color: #fff !important;\n"
"  font-size: 20px;\n"
"  font-weight: 500;\n"
"  background: #318aac;\n"
"  border: 2px solid;\n"
"  border-color: #318aac;\n"
"  position: relative;\n"
"}\n"
"\n"
"QPushButton:before {\n"
"  content:\"\";\n"
"  position: absolute;\n"
"  top: 0px;\n"
"  left: 0px;\n"
"  width: 100%;\n"
"  height: 0px;\n"
"  background: rgba(255, 255, 255, 0.1);\n"
"  transition: all 1s ease;\n"
"}\n"
"\n"
"QPushButton:hover:before {\n"
"  height: 100%;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabla_buscar_medico = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_buscar_medico.setGeometry(QtCore.QRect(50, 260, 611, 141))
        self.tabla_buscar_medico.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tabla_buscar_medico.setObjectName("tabla_buscar_medico")
        self.tabla_buscar_medico.setColumnCount(6)
        self.tabla_buscar_medico.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar_medico.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar_medico.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar_medico.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar_medico.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar_medico.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar_medico.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar_medico.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar_medico.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_buscar_medico.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 40, 201, 31))
        self.label.setObjectName("label")
        self.input_id_medico = QtWidgets.QLineEdit(self.centralwidget)
        self.input_id_medico.setGeometry(QtCore.QRect(270, 130, 151, 20))
        self.input_id_medico.setObjectName("input_id_medico")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 100, 261, 31))
        self.label_2.setObjectName("label_2")
        self.boton_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_buscar.setGeometry(QtCore.QRect(290, 180, 111, 31))
        self.boton_buscar.setObjectName("boton_buscar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 20))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegresar = QtWidgets.QAction(MainWindow)
        self.actionRegresar.setObjectName("actionRegresar")
        self.menuMenu.addAction(self.actionRegresar)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "J-MEDIC Buscar Medico"))
        item = self.tabla_buscar_medico.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Medico"))
        item = self.tabla_buscar_medico.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tabla_buscar_medico.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellido Paterno"))
        item = self.tabla_buscar_medico.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Apellido Materno"))
        item = self.tabla_buscar_medico.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cedula"))
        item = self.tabla_buscar_medico.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Turno"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Buscar Medicos</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Ingresa el ID del Medico</p></body></html>"))
        self.boton_buscar.setText(_translate("MainWindow", "Buscar"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionRegresar.setText(_translate("MainWindow", "Regresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
