# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editar Pacientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 645)
        MainWindow.setStyleSheet("*{\n"
"    background-color: rgb(0, 0, 0);\n"
"    font-family: Arial;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QMenuBar{\n"
"    text-decoration: underline rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 75 18pt;\n"
"}\n"
"\n"
"QLineEdit,QComboBox,QDoubleSpinBox,QSpinBox{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton{\n"
"  color: #fff !important;\n"
"  font-size: 20px;\n"
"  font-weight: 500;\n"
"  background: #318aac;\n"
"  border: 2px solid;\n"
"  border-color: #318aac;\n"
"  position: relative;\n"
"}\n"
"\n"
"QPushButton:before {\n"
"  content:\"\";\n"
"  position: absolute;\n"
"  top: 0px;\n"
"  left: 0px;\n"
"  width: 100%;\n"
"  height: 0px;\n"
"  background: rgba(255, 255, 255, 0.1);\n"
"  transition: all 1s ease;\n"
"}\n"
"\n"
"QPushButton:hover:before {\n"
"  height: 100%;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 10, 191, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 50, 281, 31))
        self.label_2.setObjectName("label_2")
        self.input_ApellidoP = QtWidgets.QLineEdit(self.centralwidget)
        self.input_ApellidoP.setGeometry(QtCore.QRect(330, 180, 211, 20))
        self.input_ApellidoP.setObjectName("input_ApellidoP")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 150, 91, 21))
        self.label_3.setObjectName("label_3")
        self.input_Nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Nombre.setGeometry(QtCore.QRect(60, 180, 201, 20))
        self.input_Nombre.setObjectName("input_Nombre")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 140, 181, 31))
        self.label_4.setObjectName("label_4")
        self.input_ID_Paciente = QtWidgets.QLineEdit(self.centralwidget)
        self.input_ID_Paciente.setGeometry(QtCore.QRect(460, 80, 211, 20))
        self.input_ID_Paciente.setObjectName("input_ID_Paciente")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(620, 150, 181, 31))
        self.label_5.setObjectName("label_5")
        self.input_ApeliidoM = QtWidgets.QLineEdit(self.centralwidget)
        self.input_ApeliidoM.setGeometry(QtCore.QRect(610, 180, 211, 20))
        self.input_ApeliidoM.setObjectName("input_ApeliidoM")
        self.input_sexo = QtWidgets.QComboBox(self.centralwidget)
        self.input_sexo.setGeometry(QtCore.QRect(890, 180, 201, 22))
        self.input_sexo.setObjectName("input_sexo")
        self.input_sexo.addItem("")
        self.input_sexo.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(960, 150, 61, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(130, 220, 61, 21))
        self.label_7.setObjectName("label_7")
        self.tabla_pacientes = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_pacientes.setGeometry(QtCore.QRect(10, 460, 1111, 121))
        self.tabla_pacientes.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_pacientes.setObjectName("tabla_pacientes")
        self.tabla_pacientes.setColumnCount(11)
        self.tabla_pacientes.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(10, item)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(270, 250, 41, 21))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(390, 220, 91, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(550, 250, 31, 21))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(680, 220, 61, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(950, 220, 91, 21))
        self.label_14.setObjectName("label_14")
        self.input_Telefono = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Telefono.setGeometry(QtCore.QRect(890, 250, 201, 20))
        self.input_Telefono.setObjectName("input_Telefono")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(80, 290, 171, 31))
        self.label_15.setObjectName("label_15")
        self.input_Tipo_de_sangre = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Tipo_de_sangre.setGeometry(QtCore.QRect(60, 320, 201, 20))
        self.input_Tipo_de_sangre.setObjectName("input_Tipo_de_sangre")
        self.input_Alergias = QtWidgets.QTextEdit(self.centralwidget)
        self.input_Alergias.setGeometry(QtCore.QRect(330, 330, 221, 64))
        self.input_Alergias.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.input_Alergias.setObjectName("input_Alergias")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(390, 290, 91, 31))
        self.label_16.setObjectName("label_16")
        self.boton_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_guardar.setGeometry(QtCore.QRect(780, 340, 111, 41))
        self.boton_guardar.setObjectName("boton_guardar")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(900, 330, 51, 51))
        self.label_17.setStyleSheet("image: url(:/guardar2/guardar.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.input_Peso = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.input_Peso.setGeometry(QtCore.QRect(60, 250, 201, 22))
        self.input_Peso.setObjectName("input_Peso")
        self.input_Estatura = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.input_Estatura.setGeometry(QtCore.QRect(330, 250, 211, 22))
        self.input_Estatura.setObjectName("input_Estatura")
        self.input_Edad = QtWidgets.QSpinBox(self.centralwidget)
        self.input_Edad.setGeometry(QtCore.QRect(610, 250, 211, 22))
        self.input_Edad.setObjectName("input_Edad")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(610, 340, 111, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 20))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegresar = QtWidgets.QAction(MainWindow)
        self.actionRegresar.setObjectName("actionRegresar")
        self.menuMenu.addAction(self.actionRegresar)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "J-MEDIC Editar Pacientes"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Editar Pacientes</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Ingresa el ID del paciente</p></body></html>"))
        self.input_ApellidoP.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.input_ApellidoP.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Nombre</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Apellido Paterno</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Apellido Materno</p></body></html>"))
        self.input_sexo.setItemText(0, _translate("MainWindow", "Masculino"))
        self.input_sexo.setItemText(1, _translate("MainWindow", "Femenino"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Sexo</p><p><br/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Peso</p></body></html>"))
        item = self.tabla_pacientes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Paciente"))
        item = self.tabla_pacientes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tabla_pacientes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellido Paterno"))
        item = self.tabla_pacientes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Apellido Materno"))
        item = self.tabla_pacientes.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sexo"))
        item = self.tabla_pacientes.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Peso"))
        item = self.tabla_pacientes.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Estatura"))
        item = self.tabla_pacientes.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Edad"))
        item = self.tabla_pacientes.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Telefono"))
        item = self.tabla_pacientes.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Tipo de Sangre"))
        item = self.tabla_pacientes.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Alergias"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>KG</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Estatura</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>M</p><p><br/></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Edad</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Telefono</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Tipo de Sangre</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Alergias</p></body></html>"))
        self.boton_guardar.setText(_translate("MainWindow", "Guardar"))
        self.pushButton.setText(_translate("MainWindow", "Buscar"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionRegresar.setText(_translate("MainWindow", "Regresar"))
import guardar2_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
