# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registrar Medicos.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlDatabase, QSqlQuery
from PyQt5.QtWidgets import QApplication, QDialog, QGridLayout, QMessageBox, QLabel, QPushButton, QLineEdit, QSpinBox
from PyQt5 import uic
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 501)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("*{\n"
"    background-color: rgb(0, 0, 0);\n"
"    font-family: Arial;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QMenuBar{\n"
"    text-decoration: underline rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 75 18pt;\n"
"}\n"
"\n"
"QLineEdit,QComboBox,QDoubleSpinBox,QSpinBox{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton{\n"
"  color: #fff !important;\n"
"  font-size: 20px;\n"
"  font-weight: 500;\n"
"  background: #318aac;\n"
"  border: 2px solid;\n"
"  border-color: #318aac;\n"
"  position: relative;\n"
"}\n"
"\n"
"QPushButton:before {\n"
"  content:\"\";\n"
"  position: absolute;\n"
"  top: 0px;\n"
"  left: 0px;\n"
"  width: 100%;\n"
"  height: 0px;\n"
"  background: rgba(255, 255, 255, 0.1);\n"
"  transition: all 1s ease;\n"
"}\n"
"\n"
"QPushButton:hover:before {\n"
"  height: 100%;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 40, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_Nombre = QtWidgets.QLabel(self.centralwidget)
        self.label_Nombre.setGeometry(QtCore.QRect(190, 110, 91, 31))
        self.label_Nombre.setObjectName("label_Nombre")
        self.label_ApellidoP = QtWidgets.QLabel(self.centralwidget)
        self.label_ApellidoP.setGeometry(QtCore.QRect(100, 160, 181, 31))
        self.label_ApellidoP.setObjectName("label_ApellidoP")
        self.label_ApellidoM = QtWidgets.QLabel(self.centralwidget)
        self.label_ApellidoM.setGeometry(QtCore.QRect(100, 210, 191, 31))
        self.label_ApellidoM.setObjectName("label_ApellidoM")
        self.label_Cedula = QtWidgets.QLabel(self.centralwidget)
        self.label_Cedula.setGeometry(QtCore.QRect(200, 260, 81, 31))
        self.label_Cedula.setObjectName("label_Cedula")
        self.label_Telefono = QtWidgets.QLabel(self.centralwidget)
        self.label_Telefono.setGeometry(QtCore.QRect(190, 310, 101, 31))
        self.label_Telefono.setObjectName("label_Telefono")
        self.input_Turno_2 = QtWidgets.QComboBox(self.centralwidget)
        self.input_Turno_2.setGeometry(QtCore.QRect(290, 360, 191, 21))
        self.input_Turno_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_Turno_2.setObjectName("input_Turno_2")
        self.input_Turno_2.addItem("")
        self.input_Turno_2.addItem("")
        self.label_Turno = QtWidgets.QLabel(self.centralwidget)
        self.label_Turno.setGeometry(QtCore.QRect(220, 360, 71, 31))
        self.label_Turno.setObjectName("label_Turno")
        self.input_Nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Nombre.setGeometry(QtCore.QRect(290, 110, 191, 21))
        self.input_Nombre.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_Nombre.setObjectName("input_Nombre")
        self.input_ApellidoP = QtWidgets.QLineEdit(self.centralwidget)
        self.input_ApellidoP.setGeometry(QtCore.QRect(290, 160, 191, 21))
        self.input_ApellidoP.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_ApellidoP.setObjectName("input_ApellidoP")
        self.input_ApellidoM = QtWidgets.QLineEdit(self.centralwidget)
        self.input_ApellidoM.setGeometry(QtCore.QRect(290, 210, 191, 21))
        self.input_ApellidoM.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_ApellidoM.setObjectName("input_ApellidoM")
        self.input_Cedula = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Cedula.setGeometry(QtCore.QRect(290, 260, 191, 21))
        self.input_Cedula.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_Cedula.setObjectName("input_Cedula")
        self.input_Telefono = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Telefono.setGeometry(QtCore.QRect(290, 310, 191, 21))
        self.input_Telefono.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_Telefono.setObjectName("input_Telefono")
        self.Boton_Guardar = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Guardar.setGeometry(QtCore.QRect(430, 400, 111, 41))
        self.Boton_Guardar.setStyleSheet("")
        self.Boton_Guardar.setObjectName("Boton_Guardar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 390, 51, 61))
        self.label_2.setStyleSheet("image: url(:/guardar/guardar.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setUnderline(True)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.menuMenu.setFont(font)
        self.menuMenu.setObjectName("menuMenu")
        self.menuMostrar_Medicos = QtWidgets.QMenu(self.menubar)
        self.menuMostrar_Medicos.setObjectName("menuMostrar_Medicos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegresar = QtWidgets.QAction(MainWindow)
        self.actionRegresar.setObjectName("actionRegresar")
        self.actionVer = QtWidgets.QAction(MainWindow)
        self.actionVer.setObjectName("actionVer")
        self.menuMenu.addAction(self.actionRegresar)
        self.menuMostrar_Medicos.addAction(self.actionVer)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuMostrar_Medicos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "J-MEDIC Registro de Medicos"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Registar Medicos</span></p></body></html>"))
        self.label_Nombre.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">Nombre</span></p></body></html>"))
        self.label_ApellidoP.setText(_translate("MainWindow", "<html><head/><body><p>Apellido Paterno</p></body></html>"))
        self.label_ApellidoM.setText(_translate("MainWindow", "<html><head/><body><p>Apellido Materno</p></body></html>"))
        self.label_Cedula.setText(_translate("MainWindow", "<html><head/><body><p>Cedula</p></body></html>"))
        self.label_Telefono.setText(_translate("MainWindow", "<html><head/><body><p>Telefono</p></body></html>"))
        self.input_Turno_2.setItemText(0, _translate("MainWindow", "Matutino"))
        self.input_Turno_2.setItemText(1, _translate("MainWindow", "Vespertino"))
        self.label_Turno.setText(_translate("MainWindow", "<html><head/><body><p>Turno</p></body></html>"))
        self.Boton_Guardar.setText(_translate("MainWindow", "Guardar"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuMostrar_Medicos.setTitle(_translate("MainWindow", "Lista de Medicos"))
        self.actionRegresar.setText(_translate("MainWindow", "Regresar"))
        self.actionVer.setText(_translate("MainWindow", "Ver"))


self.db = QSqlDatabase.addDatabase('QMYSQL')
self.db.setHostName("127.0.0.1")
self.db.setDatabaseName("mydb")
self.db.setUserName("root")
self.db.setPassword("root")

self.Boton_Guardar.clicked.connect(self.guardar)

def insertar(self):
        estado = self.db.open()
        if estado == False:
                QMessageBox.warning(self,"Error",self.db.lastError().text(),QMessageBox.Discard)
        else:
                nombreMedico = self.input_Nombre()
                apellidoPMedico = self.input_ApellidoP()
                apellidoMMedico = self.input_ApellidoM()
                Cedula = self.input_Cedula()
                Telefono = self.input_Telefono
                id_turnos = self.input_Turno_2()
                sql = "INSERT INTO medicos(nombreMedico, apellidoPMedico,apellidoMMedico,Cedula,Telefono,id_turnos) VALUES (:nombreMedico, :apellidoPMedico,:apellidoMMedico,:Cedula,:Telefono,:id_turnos)"
                consulta =  QSqlQuery()
                consulta.prepare(sql)
                consulta.bindValue(":nombreMedico",nombreMedico)
                consulta.bindValue(":apellidoPMedico",apellidoPMedico)
                consulta.bindValue(":apellidoMMedico",apellidoMMedico)
                consulta.bindValue(":Cedula",Cedula)
                consulta.bindValue(":Telefono",Telefono)
                consulta.bindValue(":id_turnos",id_turnos)
                estado = consulta.exec_()
                if estado == True:
                        QMessageBox.information(self,"Correcto","Datos guardados",QMessageBox.Discard)
                else:
                        QMessageBox.warning(self,"Error",self.db.lastError().text(),QMessageBox.Discard)
                self.db.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
